### PR TITLE
EntryRegistration: Implement GodotResource registration

### LINKED ISSUE #99: EntryGenerator DefaultValues (3): Support for Resources
Implement default value support for Resources and custom Resources.

The user would have to write the following:
```kotlin
@RegisterProperty
lateinit var resource: Resource //if not lateinit -> fail, customResources: just have to derive from Resource but are exported as Resource and not as custom type
```

**Implementation hints:**
- Files that need to be changed: `PropertyDefaultValueProvider` and `PropertyHintTypeMapper`
- Provide proper error messages (with Expcetions for now. MessageCollector will be implemented later)
- Default values need to be wrapped in a `Variant`
- A value type hint needs to be supplied at registration time
- Resource must be defined as lateinit and does NOT support default values! -> this must fail otherwise at compile time!
- A custom resource should be registered as just a resource and be casted back to the custom type when set by godot
- Registration should look like:  
```kotlin
property("nameOfProperty", TestingClass::propertyReference, STRING /*This is the püroperty type*/, Variant("defaultValue") /*This is the default value*/, true /**visible in editor/, DISABLED /*RPCMode*/, GODOT_PROPERTY_HINT_GLOBAL_DIR /*hint type*/, "" /*hint string*/)
```

### PR DESCRIPTION
**Pull request by chippmann**
This closes #99 and fixes the registration of properties which are not visible in the editor by not providing a default value for them.

### CODE REVIEW

File: entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/extension/KotlinTypeExt.kt [hunk 1]
```diff
@@ -1,12 +1,20 @@
...
 import org.jetbrains.kotlin.types.KotlinType
+import org.jetbrains.kotlin.types.typeUtil.supertypes
 
 
 fun KotlinType.isCoreType(): Boolean {
     return coreTypes.contains(this.toString())
 }
 
+fun KotlinType.isResource(): Boolean {
+    return this.toString() == "GodotResource"
```
Comment (raniejade) [inline entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/extension/KotlinTypeExt.kt]: are we able to check the fully qualified name? Also shouldn't this be `Resource`?

File: entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/generator/provider/ResourceRegistrationValuesHandler.kt [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+        return when (propertyHintAnnotation?.fqName?.asString()) {
+            //TODO: implement ResourceType
+            null -> ClassName("godot.gdnative.godot_property_hint", "GODOT_PROPERTY_HINT_NONE")
+            else -> throw WrongAnnotationUsageException(propertyDescriptor, propertyHintAnnotation)
+        }
+    }
+
+    override fun getHintString(): String {
+        //TODO: implement ResourceType
+        return ""
```
Comment (raniejade) [inline entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/generator/provider/ResourceRegistrationValuesHandler.kt:31]: The hint string is basically the class name of the type right?

**Review by raniejade — COMMENTED** [review]
A few comments :)

File: samples/mini-games/src/godotMain/kotlin/example/TestingClass.kt [hunk 3]
```diff
@@ -1,6 +1,7 @@
 package example
 
 import godot.annotation.*
+import godot.core.GodotResource
```
Comment (piiertho) [inline samples/mini-games/src/godotMain/kotlin/example/TestingClass.kt]: Resource is generated and so is in godot package.

**Review by piiertho — CHANGES_REQUESTED** [review]

File: entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/extension/KotlinTypeExt.kt (hunk 1 above)
Comment (chippmann) [reply entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/extension/KotlinTypeExt.kt]: with this yes `kotlinType.getJetTypeFqName(false)` but maybe there is a better solution?

File: entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/generator/provider/ResourceRegistrationValuesHandler.kt (hunk 2 above)
Comment (chippmann) [reply entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/generator/provider/ResourceRegistrationValuesHandler.kt:31]: not that I'm aware of. I didn't find any information about this in the source code. I guess it's always empty for resources?

File: samples/mini-games/src/godotMain/kotlin/example/TestingClass.kt (hunk 3 above)
Comment (chippmann) [reply samples/mini-games/src/godotMain/kotlin/example/TestingClass.kt]: ok i move the dummyClass

File: entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/generator/provider/ResourceRegistrationValuesHandler.kt (hunk 2 above)
Comment (chippmann) [reply entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/generator/provider/ResourceRegistrationValuesHandler.kt:31]: for the resource type it's not empty and it's the class name yes but that hint type annotation is not yet implemented

File: entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/extension/KotlinTypeExt.kt (hunk 1 above)
Comment (chippmann) [reply entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/extension/KotlinTypeExt.kt]: currently it's named `GodotResource` @piiertho whats the final name?

**Review by piiertho — APPROVED** [review]

File: entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/extension/KotlinTypeExt.kt (hunk 1 above)
Comment (piiertho) [reply entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/extension/KotlinTypeExt.kt]: It is named Resource :)

Comment (chippmann) [reply entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/extension/KotlinTypeExt.kt]: I renamed it :-)
