### PR TITLE
Fix/global functions

### LINKED ISSUE #168: [Master-Merge ToDo] Improve GD.print and fix frozen issue
Currently if one just wants to print a string, one has to write:
`GD.print(arrayOf(Variant("Property: ${this::rangeInt.name} -> $rangeInt")))` which is very convoluted

I propose a signature like this:
`fun print(vararg args: Any)`

### PR DESCRIPTION
**Pull request by CedNaru**
The tyranny of the single StringBuilder is over.

Resolves #168

### CODE REVIEW

File: godot-kotlin/godot-library/src/nativePublic/kotlin/godot/global/GDPrint.kt [hunk 1]
```diff
@@ -2,37 +2,40 @@ package godot.global
 
 import godot.core.Godot
 import godot.core.Variant
+import kotlin.native.concurrent.AtomicReference
```
Comment (chippmann) [inline godot-kotlin/godot-library/src/nativePublic/kotlin/godot/global/GDPrint.kt]: unused import

**Review by chippmann — CHANGES_REQUESTED** [review]

**Comment by chippmann** [comment]
Resolves #168

**Review by chippmann — APPROVED** [review]
